### ISSUE TITLE
listparkingspotstoday only returns a single parking spot

### ISSUE THREAD

**Issue by hannessolo** [berufsbildung-basel/parkit-spec#3]
Only one parking spot is returned.

I think this should be changed to return an array of `#/components/schemas/ParkingSpotWithReservationsAndVehicles`: https://github.com/berufsbildung-basel/parkit-spec/blob/e77d6bef14e3303621029779aad202b71f2551b0/api.yml#L293

**Comment by solaris007** [comment]
@hannessolo absolutely - feel free to open a PR
